# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_modif',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ajoute le'),
            preserve_default=False,
        ),
    ]
