# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170718_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichier',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fichier_post',
        ),
        migrations.AddField(
            model_name='faculte',
            name='logo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichier',
            name='nom_auteur',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Nom de l'auteur"),
        ),
        migrations.AddField(
            model_name='fichier',
            name='titre_document',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Titre de document'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom_cat',
            field=models.CharField(choices=[('Syllabus', 'Syllabus'), ('Livre', 'Livre'), ('memoire', 'Mémoire'), ('tfc', 'TFC'), ('bats', 'BATS')], max_length=12),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='nom_promo',
            field=models.CharField(choices=[('G0', 'Preparatoire'), ('G1', '1er Graduat'), ('G2', '2eme Graduat'), ('G3', '3eme Graduat'), ('L1', '1er Licence'), ('L2', '2eme Licence'), ('D1', '1er Doctorat'), ('D1', '1er Doctorat'), ('D3', '3eme Doctorat')], max_length=10),
        ),
        migrations.AlterField(
            model_name='universite',
            name='nom_recteur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
