# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170729_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichier',
            old_name='romotion',
            new_name='promotion',
        ),
    ]
