# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20170729_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='titre_auteur',
            field=models.CharField(blank=True, choices=[('Prof', 'Professeur'), ('CT', 'Chef de travaux'), ('Ass', 'Assistant')], max_length=30, null=True, verbose_name="Titre e l'auteur"),
        ),
    ]
