# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_fichier_titre_auteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='nom_cat',
            field=models.CharField(choices=[('Syllabus', 'Syllabus'), ('TP', 'Travail Pratique'), ('memoire', 'Mémoire'), ('tfc', 'TFC'), ('bats', 'BATS')], max_length=12),
        ),
    ]
